name: first workflow

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"

      - name: muline command
        run: |
          npm -v
          node -v

  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: view SW version
        run: sw_vers

  dependent-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo a string
        run: write-output "windows string"
      #- name: errore command
       #run: doesnotexist 
  